version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    # Uncomment the following lines to enable GPU acceleration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # Or 'all'
              capabilities: [gpu]
    networks:
      - ollama_net
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
    ports:
      - "8081:8081"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      # Optional: Add WebUI specific configurations here if needed
      # Example: WEBUI_SECRET_KEY=your_secret_key
    volumes:
      - open_webui_data:/app/backend/data
    networks:
      - ollama_net
    restart: unless-stopped

volumes:
  ollama_data:
  open_webui_data:

networks:
  ollama_net:
    driver: bridge

# After starting with 'docker-compose up -d', access Open WebUI at http://localhost:8081
# You can then pull the deepseek-r1 model through the WebUI or by running:
# docker exec -it ollama bash
# ollama pull deepseek-r1

